# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_pool_max_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_pick_number', models.IntegerField(default=1)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pool')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_short_code', models.CharField(max_length=10)),
                ('league_full_name', models.CharField(max_length=256)),
                ('team_short_code', models.CharField(max_length=10)),
                ('team_full_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='draftpick',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
