# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161001_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league_short_code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_short_code',
            field=models.CharField(max_length=256),
        ),
    ]
