# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161001_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpick',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
    ]
